#!/bin/bash

# Issues:
# How to determine which machine is doing the job?
# How to prevent redundancy/duplication?
# How to notify different instances that one or the other is already doing this work?
# How to determine when this task was last run so we don't overlap/miss?

# From and To should be
from='2011/05/14 11:30:00'
to='2011/05/14 11:30:00'

# We really should have
python trunk/scripts/digest_emailer.py -c /home/givaminute/config.yaml --from $from --to $to
