#--------------------------------------------------------------------
# Copyright (c) 2011 Local Projects. All rights reserved.
# Licensed under the Affero GNU GPL v3, see LICENSE for more details.
#--------------------------------------------------------------------
# DATA
insert into user_group (user_group_id, group_name, description) values (1, 'admin', 'Site admin/super users');
insert into user_group (user_group_id, group_name, description) values (2, 'moderator', 'Site moderators');
insert into user_group (user_group_id, group_name, description) values (3, 'leader', 'Reponse leaders/"endorsers"');

insert into badwords (kill_words) values
('shit fuck twat cunt blowjob buttplug dildo felching fudgepacker jizz smegma clitoris asshole bullshit bullshitter bullshitters bullshitting chickenshit chickenshits clit cockhead cocksuck cocksucker cocksucking cum cumming cums cunt cuntree cuntry cunts dipshit dipshits dumbfuck dumbfucks dumbshit dumbshits fuck fucka fucke fucked fucken fucker fuckers fuckface fuckhead fuckheads fuckhed fuckin fucking fucks fuckup fuckups kunt kuntree kuntry kunts motherfuck motherfucken motherfucker motherfuckers motherfuckin motherfucking shit shitface shitfaced shithead shitheads shithed shits shitting shitty');

INSERT INTO `keyword` (keyword) VALUES ('access');
INSERT INTO `keyword` (keyword) VALUES ('air');
INSERT INTO `keyword` (keyword) VALUES ('beautification');
INSERT INTO `keyword` (keyword) VALUES ('bicycle');
INSERT INTO `keyword` (keyword) VALUES ('biking');
INSERT INTO `keyword` (keyword) VALUES ('bronx');
INSERT INTO `keyword` (keyword) VALUES ('brooklyn');
INSERT INTO `keyword` (keyword) VALUES ('brownfields');
INSERT INTO `keyword` (keyword) VALUES ('business');
INSERT INTO `keyword` (keyword) VALUES ('cafes');
INSERT INTO `keyword` (keyword) VALUES ('carbon');
INSERT INTO `keyword` (keyword) VALUES ('cars');
INSERT INTO `keyword` (keyword) VALUES ('cleanup');
INSERT INTO `keyword` (keyword) VALUES ('climate');
INSERT INTO `keyword` (keyword) VALUES ('community');
INSERT INTO `keyword` (keyword) VALUES ('compost');
INSERT INTO `keyword` (keyword) VALUES ('composting');
INSERT INTO `keyword` (keyword) VALUES ('conservation');
INSERT INTO `keyword` (keyword) VALUES ('contamination');
INSERT INTO `keyword` (keyword) VALUES ('costs');
INSERT INTO `keyword` (keyword) VALUES ('data');
INSERT INTO `keyword` (keyword) VALUES ('demography');
INSERT INTO `keyword` (keyword) VALUES ('development');
INSERT INTO `keyword` (keyword) VALUES ('ecology');
INSERT INTO `keyword` (keyword) VALUES ('education');
INSERT INTO `keyword` (keyword) VALUES ('efficiency');
INSERT INTO `keyword` (keyword) VALUES ('emissions');
INSERT INTO `keyword` (keyword) VALUES ('empowerment');
INSERT INTO `keyword` (keyword) VALUES ('energy');
INSERT INTO `keyword` (keyword) VALUES ('environment');
INSERT INTO `keyword` (keyword) VALUES ('flowers');
INSERT INTO `keyword` (keyword) VALUES ('food');
INSERT INTO `keyword` (keyword) VALUES ('fruits');
INSERT INTO `keyword` (keyword) VALUES ('garden');
INSERT INTO `keyword` (keyword) VALUES ('gardening');
INSERT INTO `keyword` (keyword) VALUES ('gardens');
INSERT INTO `keyword` (keyword) VALUES ('grants');
INSERT INTO `keyword` (keyword) VALUES ('green');
INSERT INTO `keyword` (keyword) VALUES ('green-jobs');
INSERT INTO `keyword` (keyword) VALUES ('greener');
INSERT INTO `keyword` (keyword) VALUES ('grocery');
INSERT INTO `keyword` (keyword) VALUES ('growing');
INSERT INTO `keyword` (keyword) VALUES ('growth');
INSERT INTO `keyword` (keyword) VALUES ('harlem');
INSERT INTO `keyword` (keyword) VALUES ('health');
INSERT INTO `keyword` (keyword) VALUES ('heat');
INSERT INTO `keyword` (keyword) VALUES ('housing');
INSERT INTO `keyword` (keyword) VALUES ('infastructure');
INSERT INTO `keyword` (keyword) VALUES ('information');
INSERT INTO `keyword` (keyword) VALUES ('involvement');
INSERT INTO `keyword` (keyword) VALUES ('jobs');
INSERT INTO `keyword` (keyword) VALUES ('justice');
INSERT INTO `keyword` (keyword) VALUES ('land');
INSERT INTO `keyword` (keyword) VALUES ('legislation');
INSERT INTO `keyword` (keyword) VALUES ('manhattan');
INSERT INTO `keyword` (keyword) VALUES ('mapping');
INSERT INTO `keyword` (keyword) VALUES ('neighborhood');
INSERT INTO `keyword` (keyword) VALUES ('open');
INSERT INTO `keyword` (keyword) VALUES ('open-space');
INSERT INTO `keyword` (keyword) VALUES ('parks');
INSERT INTO `keyword` (keyword) VALUES ('partnership');
INSERT INTO `keyword` (keyword) VALUES ('performance');
INSERT INTO `keyword` (keyword) VALUES ('planning');
INSERT INTO `keyword` (keyword) VALUES ('plants');
INSERT INTO `keyword` (keyword) VALUES ('plazas');
INSERT INTO `keyword` (keyword) VALUES ('politics');
INSERT INTO `keyword` (keyword) VALUES ('popup');
INSERT INTO `keyword` (keyword) VALUES ('preservation');
INSERT INTO `keyword` (keyword) VALUES ('professional');
INSERT INTO `keyword` (keyword) VALUES ('professionals');
INSERT INTO `keyword` (keyword) VALUES ('public');
INSERT INTO `keyword` (keyword) VALUES ('quality');
INSERT INTO `keyword` (keyword) VALUES ('queens');
INSERT INTO `keyword` (keyword) VALUES ('rail');
INSERT INTO `keyword` (keyword) VALUES ('rainwater');
INSERT INTO `keyword` (keyword) VALUES ('recycling');
INSERT INTO `keyword` (keyword) VALUES ('redevelopment');
INSERT INTO `keyword` (keyword) VALUES ('research');
INSERT INTO `keyword` (keyword) VALUES ('resources');
INSERT INTO `keyword` (keyword) VALUES ('reuse');
INSERT INTO `keyword` (keyword) VALUES ('rooftops');
INSERT INTO `keyword` (keyword) VALUES ('runoff');
INSERT INTO `keyword` (keyword) VALUES ('safety');
INSERT INTO `keyword` (keyword) VALUES ('sanitation');
INSERT INTO `keyword` (keyword) VALUES ('space');
INSERT INTO `keyword` (keyword) VALUES ('speaker');
INSERT INTO `keyword` (keyword) VALUES ('staten');
INSERT INTO `keyword` (keyword) VALUES ('statistics');
INSERT INTO `keyword` (keyword) VALUES ('stormwater');
INSERT INTO `keyword` (keyword) VALUES ('sustainability');
INSERT INTO `keyword` (keyword) VALUES ('traffic');
INSERT INTO `keyword` (keyword) VALUES ('transportation');
INSERT INTO `keyword` (keyword) VALUES ('trees');
INSERT INTO `keyword` (keyword) VALUES ('vegetables');
INSERT INTO `keyword` (keyword) VALUES ('volunteer');
INSERT INTO `keyword` (keyword) VALUES ('walkways');
INSERT INTO `keyword` (keyword) VALUES ('waste');
INSERT INTO `keyword` (keyword) VALUES ('water');
INSERT INTO `keyword` (keyword) VALUES ('waterfront');
INSERT INTO `keyword` (keyword) VALUES ('workshops');
INSERT INTO `keyword` (keyword) VALUES ('youth');


